# Proposed operator-only bank ops for FSP-PUM-ENV-IDPROBE-001A-S3D-PART0-CPUTIME-REGATE-001A
# Generated by Codex; not run by Codex. No push.
$ErrorActionPreference = 'Stop'
$ExpectedHead = 'c0c6bf416f8a06777a1465e005e4aae0dbdc1bae'
$CommitMessage = 'FSP-PUM-ENV-IDPROBE-001A S3d PART0 CPU-time regate'
$Allowlist = @(
  'docs/codex/tasks/FSP-PUM-ENV-IDPROBE-001A-S3D-PART0-CPUTIME-REGATE-001A.md'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/s3d_part0_cputime_regate_runner.py'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/s3d_compute_projection_line30.0_cputime_regate.json'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/claim_ceiling'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/result.json'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/failure_manifest.json'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/s3d_operator_bank_ops_proposal_cputime_regate.ps1'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/result_wall_gate_noncompliant_v1.json'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/failure_manifest_wall_gate_noncompliant_v1.json'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/s3d_compute_projection_line30.0_wall_gate_noncompliant_v1.json'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/s3d_certificate_report_wall_gate_noncompliant_v1.json'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/s3d_null_env_report_wall_gate_noncompliant_v1.json'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/baseline_comparison_wall_gate_noncompliant_v1.json'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/ablation_report_wall_gate_noncompliant_v1.json'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/replay_report_wall_gate_noncompliant_v1.json'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/trace_wall_gate_noncompliant_v1.jsonl'
  'artifacts/FSP-PUM-ENV-IDPROBE-001A/trace_wall_gate_noncompliant_v1.csv'
)

$ActualHead = (git rev-parse HEAD).Trim()
if ($ActualHead -ne $ExpectedHead) {
  throw "HEAD pin mismatch: expected $ExpectedHead got $ActualHead"
}

git reset --

$ExistingAllowlist = @()
foreach ($Path in $Allowlist) {
  if (Test-Path -LiteralPath $Path) {
    $ExistingAllowlist += $Path
  } else {
    throw "Allowlist path missing before bank: $Path"
  }
}

git add -- $ExistingAllowlist

$Staged = @(git diff --cached --name-only)
if ($Staged.Count -ne $ExistingAllowlist.Count) {
  throw "Staged count mismatch: expected $($ExistingAllowlist.Count) got $($Staged.Count): $($Staged -join ', ')"
}

$Unexpected = @($Staged | Where-Object { $Allowlist -notcontains $_ })
if ($Unexpected.Count -ne 0) {
  throw "Unexpected staged paths: $($Unexpected -join ', ')"
}

$Deleted = @(git diff --cached --name-status | Where-Object { $_ -match '^D\s' })
if ($Deleted.Count -ne 0) {
  throw "Zero-deletion gate failed: $($Deleted -join '; ')"
}

foreach ($Path in $ExistingAllowlist) {
  Get-FileHash -Algorithm SHA256 -LiteralPath $Path | Format-List
}

git commit -m $CommitMessage -- $ExistingAllowlist

Write-Host 'Banked scoped S3d PART0 CPU-time re-gate artifacts locally. No push was performed.'
